# Generated by Django 4.0.6 on 2022-07-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='categoria',
            new_name='category',
        ),
    ]
