# Generated by Django 4.0.6 on 2022-08-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_petimage_pet_age_type_pet_status_alter_pet_pet_breed_and_more'),
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='pet_kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adoption.petkind'),
        ),
        migrations.AddField(
            model_name='product',
            name='settings',
            field=models.JSONField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.FileField(upload_to='static/assets/media/store/ProductCategories'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to='static/assets/media/store/ProductImages'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
