# Generated by Django 4.0.6 on 2022-07-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_petimage_pet_images'),
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pet_kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adoption.petkind'),
        ),
    ]
