# Generated by Django 4.0.6 on 2022-07-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_pet_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.FileField(upload_to='static/assets/media/store/ProductCategories'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to='static/assets/media/store/ProductImages'),
        ),
    ]
