# Generated by Django 4.0.6 on 2022-08-01 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/assets/media/home/HomeSlide')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='static/assets/media/home/Logos')),
                ('whatsapp_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('facebook_url', models.URLField(blank=True, max_length=250)),
                ('products_image', models.ImageField(upload_to='static/assets/media/home/HomeImages')),
                ('services_image', models.ImageField(upload_to='static/assets/media/home/HomeImages')),
                ('adoption_image', models.ImageField(upload_to='static/assets/media/home/HomeImages')),
                ('slides', models.ManyToManyField(to='home.homeslide')),
            ],
        ),
    ]
