# Generated by Django 4.0.6 on 2022-07-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homeslide_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='slides',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slides',
            field=models.ManyToManyField(to='home.homeslide'),
        ),
    ]
