# Generated by Django 4.0.6 on 2022-11-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/assets/media/adoption/PetBreed')),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/assets/media/adoption/Pet')),
            ],
        ),
        migrations.CreateModel(
            name='PetKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/assets/media/adoption/PetKind')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('age_type', models.CharField(choices=[('years', 'years'), ('months', 'months')], default='', max_length=10)),
                ('status', models.CharField(choices=[('in adoption', 'in adoption'), ('adopted', 'adopted')], default='not specified', max_length=15)),
                ('images', models.ManyToManyField(to='adoption.petimage')),
                ('pet_breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adoption.petbreed')),
                ('pet_kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adoption.petkind')),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.customer')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adoption.pet')),
            ],
        ),
    ]
