# Generated by Django 4.0.6 on 2022-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('type', 'years'), ('type2', 'months')], default='years', max_length=100),
        ),
    ]
