# Generated by Django 4.0.6 on 2022-08-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/assets/media/adoption/Pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='age_type',
            field=models.CharField(choices=[('type', 'years'), ('type', 'months')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('type', 'in adoption'), ('type', 'adopted')], default='not specified', max_length=15),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adoption.petbreed'),
        ),
        migrations.AddField(
            model_name='pet',
            name='images',
            field=models.ManyToManyField(to='adoption.petimage'),
        ),
    ]
