# Generated by Django 4.0.6 on 2022-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_pet_status_alter_pet_age_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/assets/media/adoption/Pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='images',
            field=models.ManyToManyField(to='adoption.petimage'),
        ),
    ]
