# Generated by Django 4.0.6 on 2022-07-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_petimage_pet_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adoption.petbreed'),
        ),
    ]
